export API_ROOT="/"
export API_SERVER_PORT=3003
export API_DOMAIN="http://localhost"
export API_MYSQL_HOST="database-1.cu74z0ts7ehg.us-east-2.rds.amazonaws.com"
export API_MYSQL_PORT=3306
export API_MYSQL_USER="admin"
export API_MYSQL_PASSWORD="m4ster123"
export API_MYSQL_DATABASE="database-1"
export AWS_ACCESS_KEY_ID="AKIA2SRCFREAA3RGGDTC"
export AWS_SECRET_ACCESS_KEY="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"
export API_SESSION_SECRET="somesecret"
export API_JWT_EXPIRY="90m"
export API_REFRESH_SESSION_SECRET="somesupersecret"
export API_REFRESH_EXPIRY="7d"
export API_REFRESH_REFRESH_JWT_ON_USE=0
export API_CORS_ALLOW_ORIGIN="http://localhost:8080, https://localhost:8080, http://localhost:3000, http://localhost:8081, https://localhost:8081, http://localhost:3002"
